// flow-typed signature: 42c791cc4d35fbc1e7faa6bdbf8a42b7
// flow-typed version: <<STUB>>/css-declaration-sorter_v^4.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-declaration-sorter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-declaration-sorter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-declaration-sorter/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-declaration-sorter/src/index.js' {
  declare module.exports: $Exports<'css-declaration-sorter/src/index'>;
}
