// flow-typed signature: 48aa11d0769bfdf2515a2ea2cae3604a
// flow-typed version: <<STUB>>/stylelint-prettier_v^1.0.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-prettier/recommended' {
  declare module.exports: any;
}

declare module 'stylelint-prettier/stylelint-prettier' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-prettier/recommended.js' {
  declare module.exports: $Exports<'stylelint-prettier/recommended'>;
}
declare module 'stylelint-prettier/stylelint-prettier.js' {
  declare module.exports: $Exports<'stylelint-prettier/stylelint-prettier'>;
}
